import React from "react";
import {
  IoBugOutline,
  IoRocketOutline,
  IoSyncCircleOutline,
  IoBulbOutline,
  IoBuildOutline,
  IoServerOutline,
  IoSpeedometerOutline,
  IoShieldCheckmarkOutline,
  IoBookOutline,
  IoCheckmarkDoneCircleOutline,
  IoKeyOutline,
  IoCodeSlashOutline,
  IoGitMergeOutline,
  IoPricetagOutline,
  IoStarOutline,
  IoCloudDownloadOutline,
  IoChatbubblesOutline,
  IoTerminalOutline,
} from "react-icons/io5";

export const CATEGORIES_COLORS = [
  "#FF3B30",
  "#FF9500",
  "#FFCC00",
  "#34C759",
  "#007AFF",
  "#5856D6",
  "#AF52DE",
  "#FF2D55",
  "#A2845E",
  "#8E8E93",
];

export const CATEGORIES_ICONS = [
  "IoBugOutline",
  "IoRocketOutline",
  "IoSyncCircleOutline",
  "IoBulbOutline",
  "IoBuildOutline",
  "IoLayersOutline",
  "IoServerOutline",
  "IoSpeedometerOutline",
  "IoShieldCheckmarkOutline",
  "IoBookOutline",
  "IoCheckmarkDoneCircleOutline",
  "IoKeyOutline",
  "IoCodeSlashOutline",
  "IoGitMergeOutline",
  "IoPricetagOutline",
  "IoStarOutline",
  "IoCloudDownloadOutline",
  "IoChatbubblesOutline",
  "IoTerminalOutline",
];

export const ICON_MAP: { [key: string]: React.ElementType } = {
  IoBugOutline,
  IoRocketOutline,
  IoSyncCircleOutline,
  IoBulbOutline,
  IoBuildOutline,
  IoServerOutline,
  IoSpeedometerOutline,
  IoShieldCheckmarkOutline,
  IoBookOutline,
  IoCheckmarkDoneCircleOutline,
  IoKeyOutline,
  IoCodeSlashOutline,
  IoGitMergeOutline,
  IoPricetagOutline,
  IoStarOutline,
  IoCloudDownloadOutline,
  IoChatbubblesOutline,
  IoTerminalOutline,
};

export const MAX_CATS_GRID_COLS = 3;
